### ISSUE TITLE
I2 User Epic: Data Worked

### ISSUE THREAD

**Issue by vanhoofa3995** [vanhoofa3995/CTS285#16]
As a user, I want to be able to have random generated mathematical problems from a database to solve.
- [x] Create mathematical problems
- [x] Initialize a Database
- [x] Randomly generated problems
- [x] Run Answer Checker
